spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100  
  profiles:
    active:
    - dev  
---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:./roaster-prod
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
roaster: 
  upload-path: uploads-prod
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:roaster-dev
roaster: 
  upload-path: uploads-dev
---
spring:
  profiles: test
roaster: 
  upload-path: uploads-test